#!/bin/bash

# NAME
#    cvs-sync - synchronization of the POs and status report

# SYNOPSIS
#    cvs-sync [OPTIONS] .../www-TEAM

# DEPENDENCIES
#    * required: cvs, msgmerge (from the gettext package);
#    * optional: git, gnun-add-fuzzy-diff (from the gnun package), mutt.

# DESCRIPTION
#    cvs-sync synchronizes the local www directory with the CVS repository
#    on gnu.org, then www-team with the local www, and reports the differences.
#
#    Method:
#    1. cvs-sync calls 'cvs update' in www.
#    2. If there are differences with www-team, it calls msgmerge to merge
#       them, and adds diffs to fuzzy strings if gnun-add-fuzzy-diff is found.
#    3. It lists the POs that need updating and the number of fuzzy or
#       untranslated strings, as well as the POs that have been modified or
#       lack a counterpart in www (possibly indicating that they are new
#       translations).
#    4. POs that are up-to-date in www but not in www-team are copied from www
#       to www-team.
#    5. Up-to-date POs that differ but have the same PO-Revision-Date in www
#       and www-team are copied from www to www-team, but the version in
#       www-team is saved. 
#    6. If any POs are present in www but not in www-team, they are installed
#       in www-team.
#    7. If a PO editor has been specified, the outdated PO files are displayed
#       unless the -n switch is used.
#    8. [Git repo only] After the report, and optionally the POs, have been
#       displayed, the user is prompted to send the list of outdated POs to a
#       specified address and commit them to the Git repo. This requires
#       setting the email address and subject line. The message is sent with
#       Mutt.
#    9. [Git repo only] The up-to-date POs that were copied to www-team are
#       committed to Git. This could be extended to CVS repos, but the commits
#       would be irreversible.
#
#    Requirements:
#    * www and www-team must have the same parent directory.
#    * www-team must contain the working copies of the PO files.
#    * www must contain the unmodified PO files (and the corresponding
#      originals, needed for transvalidation). The POTs are not needed.

# OPTIONS AND CURRENT SETTINGS
#    Displayed by:   cvs-sync -h
#
#    Configuration file:
#    The command-line parameters can be set once and for all in a configuration
#    file (also used by transvalid-batch, www-commit, micro-www-checkout, and
#    check-links), with the syntax:
#       parameter1="value1"
#       parameter2="value2"
#    This configuration overrides the default settings but is superseded by the
#    command line. In particular, a PO editor (e.g. gtranslator) can be
#    set with the "-g" option if the configuration specifies a normal GUI
#    editor (e.g. gedit).
#    The configuration file is defined under "Parameters".

#==============================================================================

set -e
set -o pipefail

function version () {
cat <<EOF
${0##*\/} version 0.2
Copyright (C) 2013, 2015-2017, 2019 Thérèse Godefroy
You may redistribute this script and/or modify it under the terms
of the Creative Commons CC0 license.
EOF
}

function usage () {
cat <<EOF

Usage: ${0##*\/} [OPTIONS] .../www-TEAM

  The script assumes the context of www.gnu.org. It synchronizes the
  local reference directory (www) with the CVS repository, and the
  working directory (www-team) with www, then reports the status of
  the POs. www and www-team must have the same parent directory, and
  the local modifications must be made in www-team.

Options:
  -p PO_EDITOR         [$poeditor]
      Specify a PO editor. If none, POs are not displayed.

  -n  Do not display the outdated POs in the PO editor.

  -a TEAM@ADDRESS       [$address]
      Specify the address of the team mailing list (optional).
      The email will be sent with Mutt.

  -s "SUBJECT LINE"     [$subject]

  -V  Display version info and exit.
  -h  Display this help and exit.

The parameters can be specified in a configuration file:
      $conf
One line per parameter, with syntax: param='VALUE'

Report bugs to <godef.th@free.fr>

EOF
}


## Parameters

conf="$HOME/.profile"
teamdir=""
poeditor=""
display=true
address=""
subject="Outdated POs $(date +"%y-%m-%d")"

test -s "$conf" && source $conf

# Parse the command line.
OPTIND=1
while getopts "h?Vp:na:s:" opt; do
  case "$opt" in
    h | \? ) usage; exit 0 ;;
    V ) version; exit 0 ;;
    p ) poeditor=$OPTARG ;;
    n ) display=false ;;
    a ) address=$OPTARG ;;
    s ) subject=$OPTARG ;;
  esac
done
shift $((OPTIND-1))
[ "$1" = "--" ] && shift

MSGMERGE=$(which msgmerge)
MSGATTRIB=$(which msgattrib)
if [ -e "$HOME/bin/gnun-add-fuzzy-diff.1" ]; then
  FUZZY_DIFF=$HOME/bin/gnun-add-fuzzy-diff.1
else
  FUZZY_DIFF=$(which gnun-add-fuzzy-diff) ||
    echo "*** gnun-add-fuzzy-diff was not found."
fi
if [ -n "$poeditor" ] && [ -z "$(which $poeditor)" ]; then
  echo "*** The specified PO editor is not installed."
  poeditor=""
fi
MUTT=$(which mutt) ||
  echo "*** No email will be sent because Mutt is not installed."


## Functions

function close_term () {
  echo -e '\n*** Close the terminal window or press Return.'; read OK
  test -z "$OK" && exit $1
}

function check_fuzz () {
  # Unfuzz if add-fuzzy-diff didn't detect any change.
  sed -i '/^# || No change/,/^msgid/ { /^msgid/p;d }' "$1"
  # Check for non-deprecated fuzzy strings.
  fuzzy=$(grep -A1 '^#, fuzzy' "$1" |
          sed '/fuzzy/ {N; s,\n,,'} |
          sed -e '/^#, fuzzy#~/d' |
          grep -c '^#, fuzzy')

  # Check for untranslated strings.
  untr=$(sed -n '/^msgstr ""[[:space:]]*$/ {N;/\n[[:space:]]*$/p}' "$1" |
       grep -c msgstr) || true
  if test "$fuzzy" != "0" -o "$untr" != "0"; then
    return 3
  else
    return 4
  fi
}

#====================
echo "${0##*\/} - synchronization and status report"

## Team directory input

test -n "$1" && teamdir=$1
if test ! -d "$teamdir"; then
  echo -e "\n*** Please specify your team directory."; read teamdir
fi
teamdir=${teamdir%\'}; teamdir=${teamdir#\'}
# Make sure it can be reached.
cd "$teamdir" \
|| (echo 1>&2 "!!! Directory $teamdir doesn't exist."; close_term 1)
# Make the path absolute.
teamdir="$(pwd)"


## Update www.

# Make sure www can be reached,...
cd ../www 2>/dev/null ||
  (echo 1>&2 "!!! The www directory doesn't exist or is not reachable.";
  close_term 1)
# ... and is a CVS directory.
test -d CVS ||
  (echo 1>&2 "!!! $wwwdir is not a CVS directory."; close_term 1)
wwwdir="$(pwd)"

cvs update || close_term 1


## Synchronize www-team with www, and report.

cd "$teamdir"

# For those who use Git...
if test -d ".git"; then
  # Find the current branch.
  curr_branch=$(git rev-parse --abbrev-ref HEAD)
  if [ "$curr_branch" != 'master' ]; then
    echo -e "\n!!! Please move to branch master."
    close_term 1
  fi
  git pull || true
fi

# Create temporary files.
po_team_list=$(mktemp -t syn.XXXXXX) || close_term 1
po_www_list=$(mktemp -t syn.XXXXXX)  || close_term 1
po_www_list1=$(mktemp -t syn.XXXXXX) || close_term 1
po_www=$(mktemp -t syn.XXXXXX)       || close_term 1
po_team1=$(mktemp -t syn.XXXXXX)     || close_term 1
trap 'rm -f "$po_team_list" "$po_www_list" "$po_www_list1" "$po_www" \
            "$po_team1"' EXIT

# List the POs in www-team.
find . -name "*.po" | sort | sed '/server\/gnun\//d' > $po_team_list

# Get language code of the team.
lang="$(head -n1 $po_team_list)"
lang=${lang%.po}
lang=${lang##*.}

# List the POs in www.
find "$wwwdir" -type f -name "*.$lang.po" |
  sed "s|$wwwdir|.|;s|po/||;/server\/gnun\//d" | sort > $po_www_list

# Delete the output of the previous run.
rm -f ../update-report ../update-list ../modified-list

# Build the report.
echo

while read po_team; do

  diff_test=0
  fuzz_test_www=0
  fuzz_test_team=0

  section=${po_team%/*}; section=${section#./}
  basename=${po_team##*/}

  # Test for the presence of the corresponding PO in www, then eliminate
  # some trivial differences and diff the 2 versions of the PO.
  if test -s "../www/$section/po/$basename"; then
    sed 's,charset=utf-8,charset=UTF-8,' \
      "$wwwdir/$section/po/$basename" > "$po_www"
    sed 's,charset=utf-8,charset=UTF-8,' "$po_team" > "$po_team1"
    diff -uB "$po_www" "$po_team1" > /dev/null 2>&1 || diff_test=$?

    case $diff_test in
      # There is a difference: merge non-obsolete strings and add the wdiff
      # between old and new msgids.
      1 ) $MSGATTRIB --no-obsolete "$wwwdir/$section/po/$basename" > "$po_www" ||
              (2>&1 && close_term $?)
          $MSGMERGE -U -q --previous "$po_team" "$po_www" || (2>&1 && close_term $?)
          if [ -n "$FUZZY_DIFF" ]; then
            $FUZZY_DIFF -i "$po_team"
            sed -i '/^# || No change/,/^msgid/ { /^msgid/p;d }' "$po_team"
          else
            echo "No fuzzy diff."
          fi
    ;;
      # There is no difference: do nothing.
      0 )
    ;;
      * ) echo "!!! $po : Error in the diff test."
    ;;
    esac

    # Test for fuzz in www and www-team.
    check_fuzz "$po_www"  || fuzz_test_www=$?
    check_fuzz "$po_team" || fuzz_test_team=$?

    case $fuzz_test_team in
      # Fuzz in www-team
      3 ) case $fuzz_test_www in
            # Fuzz in www: the PO needs updating.
            3 ) echo "$po_team : $fuzzy fuzzy and $untr untranslated."
               if [ "$po_team1" != "$po_www" ]; then
                 echo "$po_team : $fuzzy fuzzy and $untr untranslated messages." \
                   >> ../update-report
               fi ;;
            # No fuzz in www: most likely the updated version was
            # committed directly to www.
            4 ) cp -b $wwwdir/$section/po/$basename $po_team
                echo $section/$basename >> ../modified-list ;;
            * ) echo "$po_team : !!! Error in the www fuzz test." ;;
          esac
    ;;
      # No fuzz in www-team
      4 ) case $fuzz_test_www in
            # Fuzz in www: the PO has been updated.
            3 ) echo "$po_team seems ready to post." ;;
            # No fuzz in www:
            4 ) if [ "$diff_test" != "0" ]; then
                  # Same PO-Revision-Date: most likely the PO was reformatted
                  # by GNUN. Copy the www version to www-team, but save the old
                  # file in case the PO had been modified without updating
                  # PO-Revision-Date.
                  if [ "$(grep 'PO-Revision-Date' $po_team)" = \
                       "$(grep 'PO-Revision-Date' $po_www)" ]; then
                    cp -b $wwwdir/$section/po/$basename $po_team
                    echo $section/$basename >> ../modified-list
                  else
                    echo "$po_team : versions in www and www-team differ."
                  fi
                fi ;;
            * ) echo "$po_team : !!! Error in the www fuzz test." ;;
          esac
    ;;
      * ) echo "$po_team : !!! Error in the www-team fuzz test."
    ;;
    esac

  # There is no corresponding PO in www:
  else
    echo "$po_team : new translation or misplaced/renamed PO."
  fi


## Add missing POs to www-team.

  # If the PO is also listed in $po_www_list, remove it from that list.
  grep -v "$po" $po_www_list > $po_www_list1 || true
  mv $po_www_list1 $po_www_list

done < $po_team_list

# If any POs are left in $po_www_list, add them to www-team.
if [ -s "$po_www_list" ]; then
  echo -e "\n*** Also, the following files exist in www, but not in www-team.
    They will be added to www-team."
  while read po_www; do
    echo $po_www
    section=${po_www%/*}; section=${section#.\/}
    basename=${po_www##*/}
    install -Dm644 "$wwwdir/$section/po/$basename" "$po_www"
  done < $po_www_list
  if test -d .git; then
    git add $(< $po_www_list)
    git commit -m "Add missing POs." $(< $po_www_list)
  fi
fi


## Display / advertise / commit outdated POs.

if [ -f ../update-report ]; then
  sed -e 's,^\./,,' -e 's, .*,,' ../update-report > ../update-list

  # Display the POs if a PO editor is set, unless the -n switch is used.
  if [ "$display" = true ]; then
    if [ -n "$poeditor" ]; then
      $poeditor $(< ../update-list) &
    fi
  fi

  if [ -d .git ]; then
    git add $(< ../update-list)
    # Optionally send the list of outdated POs to the team and commit the POs.
    # (This depends on the workflow.)
    if [ -n "$MUTT" ] && [[ "$address" == *@* ]] && [ -n "$subject" ]; then
      echo -e "\n*** Send the report to the mailing list and commit the POs?
          \"Yes\" = [Enter]    \"No\" = any other key\n"
      read -s -n1 OK
      if test -z "$OK";  then
        $MUTT -s "[cvs-sync] $subject" -i ../update-report -- $address < "."
        git commit -m "$subject" $(< ../update-list)
      fi
    fi
  fi
else
  echo -e "\n*** No new outdated PO."
fi

if [ -f ../modified-list ]; then
  echo -e "\n*** Modified files with same PO-Revision-Date, copied to www-team:"
  cat ../modified-list
fi

echo -e "\n*** Done."

close_term 0
