#!/bin/bash

# NAME
#    micro-www-checkout - check out a subset of www for transvalid-batch

# SYNOPSIS
#    micro-www-checkout [-u SAVANNAH_USER] [-c] [-a] [LANG]
#                       (options first)

# DEPENDENCIES
#    cvs, rsync

# DESCRIPTION
#    This script checks out the files required to use cvs-sync,
#    transvalid-po and transvalid-batch. Synchronization and transvalidation
#    with GNUN require some additional files. 
#
#    Method:
#    1. Directories:
#       - If both www and www-LANG (also called www-TEAM) exist, they should
#         have the same parent.
#       - The script can be called from www-LANG, www or their parent dir.
#       - If the script is called from www-LANG, any other LANG argument
#         is dropped. Otherwise, LANG must be given as a command-line
#         argument or as user input.
#       - The same www dir can be used for several languages.
#       - If www-LANG doesn't exist, it is optionally created.
#    2. A list of the potentially useful files is obtained from a dry run of
#       rsync on the CVS repository, exluding irrelevant directories and
#       keeping only files with .po and .html extensions.
#    3. The rsync list is further processed to build a checkout list
#       containing: 
#       - POs that reside in www (*.LANG.po);
#       - unGNUNified translations (*.LANG.html);
#       - English originals (*.html) that correspond to POs from www and/or
#         www-LANG.
#    4. The listed files are checked out by cvs, using a login if provided,
#       otherwise anonymous. (The Savannah user name can be entered on the
#       command line or in the "savannah_user" variable around line 84.)
#       If www already exists, it is simply updated.
#    5. The POs that are found in www but not in www-LANG are optionally added
#       to www-LANG.
#
#    To make a new translation, the POT file must be downloaded once to
#    create the PO, but it doesn't need to be tracked. After the new PO is
#    added to www-LANG, micro-www-checkout can be run again to add the
#    English original to www.

# OPTIONS 
#    Displayed by "micro-www-checkout -h".
#    The Savannah user name can be defined in a configuration file, as for
#    cvs-sync and www-commit.

#==============================================================================

set -e

function version () {
cat <<EOF
${0##*\/} version 0.2
Copyright (C) 2013, 2016, 2019 Thérèse Godefroy
You may redistribute this script and/or modify it under the terms
of the Creative Commons CC0 license.
EOF
}

function usage () {
cat <<EOF

Usage:
  ${0##*\/} [-u SAVANNAH_USER] [-c] [-a] [LANG]
            (options first)
    
  This script checks out a subset of the www.gnu.org cvs repo,
  essentially *.LANG.po and corresponding *.html, for use with
  cvs-sync, transvalid-po and transvalid-batch.

  If the www-LANG directory doesn't exist, it is optionally created.

Options and current settings:
  -u SAVANNAH_USER               [$savannah_user]
      Specify your login if you have write access to www (optional).
  -c  Create the team directory (www-LANG) if it doesn't exist.
  -a  Add missing POs to www-LANG.
  -V  Display version info and exit.
  -h  Display this help and exit.

Report bugs to <godef.th@free.fr>

EOF
}

function close_term () {
  sleep 10
  exit $1
}

# Initial parameters:
conf="$HOME/.profile"
savannah_user="anonymous"
create_teamdir=""
add_missing=""
test -s "$conf" && source $conf

# Parse the command line.
OPTIND=1
while getopts "h?Vu:ca" opt; do
  case "$opt" in
    h | \? ) usage; exit 0 ;;
    V ) version; exit 0 ;;
    u ) savannah_user=$OPTARG ;;
    c ) create_teamdir=1 ;;
    a ) add_missing=1 ;;
  esac
done
shift $((OPTIND-1))
[ "$1" = "--" ] && shift

# Get the language code...
if [[ "$PWD" =~ 'www-' ]]; then  # ... from the name of the team dir,
  l=${PWD#*www-}
elif [ -n "$1" ]; then           # ... or from the command line,
  l=$1
else                             # ... or from user input.
  echo "Please enter a language code."
  read l
fi

# Test the validity of the language code.
ref_lang_codes='af ar az bg bn bs ca cs da de el en eo es et fa fi fr gl he \
hr hu id it ja kn ko mk ml lt nb nl nn pl pt pt-br ro ru sh sk sl sq sr sv ta \
te th tl tr uk uz vi zh-cn zh-tw'

[[ "$ref_lang_codes" =~ "$l" ]] ||
  (echo 1>&2 "!!! Not a valid language code."; close_term 1)
lang=$l

echo "language code: $lang"

if [[ "$PWD" =~ www ]]; then
  cd ../
fi

# Optionally create www-LANG if it doesn't exist.
if [ ! -d www-$lang ] && [ "$create_teamdir" == '1' ]; then
  echo "Creating the www-$lang directory."
  mkdir www-$lang || (echo 1>&2 "Can't make www-$lang."; close_term 1) 
fi


## Select files to check out.

# Create temporary files.
TMP1=$(mktemp -t co.XXXXXX) || (echo 1>&2 "Can't make TMP1"; exit 1)
TMP2=$(mktemp -t co.XXXXXX) || (echo 1>&2 "Can't make TMP2"; exit 1)
TMP3=$(mktemp -t co.XXXXXX) || (echo 1>&2 "Can't make TMP3"; exit 1)
TMP4=$(mktemp -t co.XXXXXX) || (echo 1>&2 "Can't make TMP4"; exit 1)
TMP5=$(mktemp -t co.XXXXXX) || (echo 1>&2 "Can't make TMP5"; exit 1)
trap 'rm -f "$TMP1" "$TMP2" "$TMP3" "$TMP4" "$TMP4"' EXIT

# List the POs in www-LANG.
if [ -d "www-$lang" ]; then
  find www-$lang -name '*.po' > $TMP2
fi

echo "${0##*\/} - create a minimized www directory for $lang
"
# List the files in the www repository with a dry run of rsync, excluding
# some irrelevant directories and files. The destination directory is
# specified to avoid listing the file attributes, but it is not created.
rsync -anv --exclude "Attic" \
           --exclude "server/source/" \
           --exclude "server/staging/" \
           --include "software/po/" \
           --exclude "software/*/" \
           --exclude "www/www*/" \
           --exclude "server/gnun/" \
           --include "*.po,v" \
           --include "*.html,v" \
           --include "*/" \
           --exclude "*" \
           --prune-empty-dirs \
  rsync://cvs.sv.gnu.org/web/www/www www-cvs/ > $TMP1

# Weed out the rsync messages and the directories, and remove the ",v"
# extension.
sed -i -e '/^www/!d' \
       -e '/\/$/d' \
       -e 's:,v$::' $TMP1

# Select POs in www that have counterparts in www-LANG.
sed -i "s:^www-$lang:www:" $TMP2               # *LANG.po in www-LANG
sed "s:\([^/]*$lang\\.po\)$:po/\1:" $TMP2 > $TMP3 

# Select POs in www (some of them may not be in www-LANG).
grep "[./]$lang\.po$" $TMP1 > $TMP2 || true    # *LANG.po in www

# Figure out which POs are in www but not www-LANG.
while read f; do
  grep -q "$f" $TMP3 || echo "$f" >> $TMP4
done < $TMP2  # POS in www

# Add the corresponding originals to the checkout list.
sed "s:po/\([^/]*\)\\.$lang\\.po$:\1.html:" $TMP2 > $TMP3
cat $TMP3 >> $TMP2                              # ==> *.html

#### If some translations are not GNUNified, uncomment (1) to (3). #####

# Select all HTML translations...
#grep ".$lang.html$" $TMP1 > $TMP3 || true      # (1)
#cat $TMP3 >> $TMP2                             # (2) *.LANG.html
# ... and the corresponding originals.
#sed "s:$lang\.html$:html:" $TMP3 >> $TMP2      # (3) ==> *.html

# Sort alphabetically and remove duplicates.
sort $TMP2 | uniq > $TMP3

# Make sure all the selected files exist (some POs may not correspond to any
# originals because they have been renamed or misplaced, or the originals
# have been removed from the repository).
while read f; do
  grep "$f" $TMP1 >> $TMP5 || true
done < $TMP3


## Check out the selected files.

if [ -s "$TMP5" ]; then
  # Define the protocole.
  if test -n "$savannah_user" -a "$savannah_user" != "anonymous"; then
    protocole="ext"
  else
    protocole="pserver"
  fi
  echo "*** Creating or updating the www directory.
"
  cvs -z3 -d:$protocole:$savannah_user@cvs.sv.gnu.org:/web/www co $(< $TMP5)
else
  echo  1>&2 "!!! There is no file in the checkout list."; close_term 1
fi

if [ "$add_missing" == "1" ] && [ -s "$TMP4" ]; then
  cd www-$lang
  echo "*** Adding missing POs to www-$lang."

  while read f; do
    f1=${f/\/po\//\/} && f1=${f1/www\//}
    dir=$(dirname "$f1")
    mkdir -p $dir
    cp ../"$f" "$f1"
  done < $TMP4
fi

exit 0
