#!/bin/bash

# NAME
#    transvalid-po -- converts a PO file to HTML and validates both

# SYNOPSIS
#    transvalid-po [-d] [-u] [-m ORIGINAL_FILE] PO_FILE
#                  (options first)

# DEPENDENCIES
#    po4a (which depends on gettext, perl, etc.),
#    xmllint (Debian package libxml2-utils),
#    DTD XHTML 1.0 from W3C (Debian package w3c-dtd-xhtml),
#    html5.dtd from the GNUN package (GNUN doesn't have to be installed).
    
#    There are copies of the DTDs in the script directory (files
#    xhtml1-strict.dtd and html5.dtd).

# DESCRIPTION
#    transvalid-po generates a translated page from a PO file and the
#    corresponding original HTML. Two possibilities:
#    * www and www-team are not installed locally, in which case both the PO
#      and the original HTML must be specified.
#    * The PO is in www-team (or in a directory named www-* with the same
#      parent as www, or in www itself), and the corresponding HTML is in www.
#      In this case the original doesn't need to be specified. Thus the same
#      www-team can be shared by several languages. [A reduced version of www
#      containing the originals and the canonical POs (for use by cvs-sync) can
#      be checked out using the script "micro-www-checkout".]
#    The translated page is created in the directory that contains the PO.
#
#    Requirement:
#      xhtml1-strict.dtd and html5.dtd are assumed to be in the same directory
#      as the script. Otherwise, specify their absolute path under
#      “Dependencies”.
#
#    Functions:
#    * a simplified header and the missing tags are added to the original
#      HTML; the includes are turned into makeshift web pages to allow
#      validation (which is not possible with GNUN, except within a
#      fully-regenerated web page);
#    * to make proofreading of the HTML easier, both in the web browser and
#      the text editor, the "GNUN-split" tags of the template [0] are replaced
#      with <br />\n/*split*/\n<br /> ;
#    * the translated page is generated with po4a-translate;
#    * the page is validated with xmllint;
#    * the relative links to gnu.org articles are replaced with absolute links;
#    * the PO is reformatted and validated with msgcat;
#    * the revision date is updated;
#    * (optionally) the obsolete messages and Oudated-Since line are deleted.
#
#    [0] https://www.gnu.org/software/trans-coord/manual/gnun/gnun.html#Splitting-Long-Passages

# OPTIONS
#    Displayed by:   transvalid-po -h

#==============================================================================

set -e
set -o pipefail

function version () {
cat <<EOF
${0##*\/} version 0.3
Copyright (C) 2013, 2015, 2016, 2019, 2020, 2024 Thérèse Godefroy
You may redistribute and/or modify this script under
the terms of the GNU General Public License, v.3+
(because it borrows from GNUN, which is under GPLv3+).
EOF
}

function usage () {
cat <<EOF

${0##*\/} - converts a PO to HTML and validates both

Usage: transvalid-po [-d] [-m ORIGINAL_FILE] PO_FILE
                         (options first)

  The script can be used without option if the context is that of
  www.gnu.org, meaning that:
  - the PO file is at the proper place in the www-team directory
    (named www-*) or in www itself;
  - the corresponding original is at the proper place in www;
  - www-* and www have the same top directory.
  Otherwise, the original must be given with the -m option or
  entered at the prompt.

Options:
  -d  Delete obsolete messages if up to date (default: false)
  -u  Delete Outdated-Since if up to date (default: false)
  -m ORIGINAL_FILE
      Absolute or relative path to the original HTML
  -V  Display version info and exit
  -h  Display this help and exit

Report bugs to <godef.th@free.fr>
EOF
}

function close_or_exit () {
# turns off interactivity and lets the terminal close normally if the script
# is called from transvalid-batch.
if test "$batch" == "1"; then
  exit $exit_code
else
  echo -e '\n*** Close the terminal window or press Return.'; read OK
  test -z "$OK" && exit $?
fi
}


## Dependencies:

MSGMERGE=$(which msgmerge) \
|| echo "    msgmerge is not installed.
    The malware pages won't be merged with their compendium."
PO4A_TRANSLATE=$(which po4a-translate) \
|| (echo "!!! po4a-translate is not installed - exiting."; close_or_exit 1)
XMLLINT=$(which xmllint) \
|| (echo "!!! xmllint is not installed - exiting."; close_or_exit 1)
MSGCAT=$(which msgcat) \
|| (echo "!!! msgcat is not installed - exiting."; close_or_exit 1)
FUZZY_DIFF=$(which gnun-add-fuzzy-diff) \
|| (echo "!!! gnun-add-fuzzy-diff is not installed - exiting."; close_or_exit 1)

# xhtml1-strict.dtd, html5.dtd and entity definitions (xhtml-lat1.ent,
# xhtml-special.ent, and xhtml-symbol.ent) are assumed to be in the same
# directory as the script. Otherwise, specify their path (without a trailing
# slash).
#DTD=${0%\/*}
DTD=/usr/local/share/gnun

## Parameters

# Test whether the script is called from transvalid-batch. The -s option
# singles out the last instance of the script.
p=$(pidof -x -s transvalid-batch) || true
if test "$p" == "$PPID"; then
  batch=1
fi

delout=1  # Delete Outdated-Since if up to date.
delobs=0  # Delete obsolete messages.

# Parse the command line.
OPTIND=1
while getopts "h?Vdum:" opt; do
  case "$opt" in
     h | \? ) usage; exit 0 ;;
     V ) version; exit 0 ;;
     d ) delobs=1 ;;
     u ) delout=1 ;;
     m ) original=$OPTARG ;;
  esac
done
shift $((OPTIND-1))
[ "$1" = "--" ] && shift


## Functions

function check_gnun_slot () {
  # Makes sure a GNUN-SLOT marker hasn't been copied to the msgstr.
  if grep 'msgstr "\*GNUN-SLOT' $1; then
    echo "!!! There is a GNUN-SLOT marker in the translation. If
    you don't have translator's notes/credits, you should
    replace it with a space."
    close_or_exit 1
  fi
}

function check_fuzz () {
  # Check for fuzzy strings that are not deprecated.
  fuzzy=$(grep -A1 '^#, fuzzy' "$1" |
          sed '/fuzzy/ {N; s,\n,,'} |
          sed -e '/^#, fuzzy#~/d' |
          grep -c '^#, fuzzy') 
  
  # Check for untranslated strings.
  untr=$(sed -n '/^msgstr ""[[:space:]]*$/ {N;/\n[[:space:]]*$/p}' "$1" |
         grep -c msgstr)
  if [ "$fuzzy" != "0" ] || [ "$untr" != "0" ]; then
    echo "!!! $fuzzy fuzzy and $untr untranslated strings."
    return 3
  else
    return 0
  fi
}

function fix_html () {
# adds a minimal HTML header and the missing tags, defines the xmllint options,
# depending whether the document is using HTML5 or not, then inactivates the
# SSI directives.

###  This will not work when the header is expanded.  ###

  cat - "$1" > "$2" << EOF
<!DOCTYPE html SYSTEM "$DTD/html5.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="$lang" lang="$lang">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/layout.min.css" media="screen" />
<link rel="stylesheet" type="text/css" href="/style.fr.css" media="all" />
EOF

  # If this is a templated page, add missing tags and inactivate SSIs.
  if grep 'include virtual="/server/banner\.' "$2" > /dev/null; then
    # Special case of pages with a side menu.
    if grep '<div class="nav"' "$2" > /dev/null; then
      sed -i -e '/virtual="\/server\/banner\./c</head><body><div>' \
             -e 's/<!--#/<!-- /g' "$2"
    else
      sed -i -e '/virtual="\/server\/banner\./c</head><body><div><div>' \
             -e 's/<!--#/<!-- /g' "$2"
    fi
  # If this is an include or something similar, add missing tags.
  else
    # Special case of side-menu includes.
    if grep '<div id="navlinks">' "$2" > /dev/null; then
      sed -i -e '/href="\/style.fr.css"/ a<title></title></head><body><div>' \
             -e '$a</body></html>' "$2"
    else
      sed -i -e '/href="\/style.fr.css"/ a<title></title></head><body>' \
             -e '$a</body></html>' "$2"
    fi
  fi
}

function remove_last_update () {
# removes the "Updated:" date to match the msgid, otherwise po4a won't
# accept the translation.
  sed -i '/$Date:/d' "$1"
}

function add_split_tags () {
# is adapted from function "add-gnun-tags" of the www GNUmakefile.
  sed -i -e '/<span[[:space:]]*$$/{:egin;N; />[^\n]*$$/! begin};' \
         -e 's,<span[[:space:]]\+class="gnun-split"></span>,\
<br />\n/*split*/\n<br />,' "$1"
}

function update_po_header () {
# updates the revision date.
  date=$(date +'%F %R%z')
  sed -i "s,\\(Revision-Date: \\).*,\\1$date\\\\n\"," "$1"
}

function delete_outdated () {
  sed -i -e '/Outdated-Since/d' $1
}

function delete_obsolete () {
# removes obsolete strings.
  sed -i -e '/^# |/d' \
         -e '/^#| /d' \
         -e '/#, fuzzy/ {N; /#, fuzzy\n#~| msgid/d}' \
         -e '/^#~/d'  $1
  sed -i ':a;/^[ \n]*$/{$d;N;ba}' $1
}

function create_addendum () {
# creates po4a addenda for translator's notes and translator's credits.
  echo "PO4A-HEADER:mode=after;position=$3;beginboundary=^" > "$4"
  echo >> "$4"
  sed -e '/*GNUN-SLOT: TRANSLATOR.S '"$2"'*/,/#. type: Content of:/!d' \
      -e '/GNUN-SLOT/d' -e '/^#/d' -e 's/^msgstr "//' \
      -e ':egin /"$/ {N; s,"\n",,; begin}' \
      -e 's,\\",",g' -e 's,\\n,\n,g' "$1"  >> "$4"
  sed -i 's,"$,,' "$4"
  echo '<br /><br />' >> "$4"
}

function make_links_absolute () {
# replaces relative links to gnu.org articles with absolute links, otherwise
# they are inactive.
  sed -i 's,href="/,href="http://www.gnu.org/,g' "$1"
}

function fix_space () {
  sed -i '
      s, ;, ;,g
      s, :, :,g
      s, !, !,g
      s, ?, ?,g
      s, », »,g
      s,« ,« ,g
      /^"X-Generator: /d
      /^"Plural-Forms: /d
    ' $1
}

#====================

top=$(mktemp -t tvp.XXXXXX)         || close_or_exit 1
merged=$(mktemp -t tvp.XXXXXX)      || close_or_exit 1
master=$(mktemp -t tvp.XXXXXX)      || close_or_exit 1
add_notes=$(mktemp -t tvp.XXXXXX)   || close_or_exit 1
add_credits=$(mktemp -t tvp.XXXXXX) || close_or_exit 1
trap 'rm -f "$top" "$merged" "$master" "$add_notes" "$add_credits"' EXIT

## Get the PO file and check it.

po="$1"
if test ! -f "${po}"; then
  echo "*** Please enter a PO file."; read po
fi

po=${po#\'}; po=${po%\'}
test -s "$po" -a  "${po%.po}" != "$po" \
|| (echo 1>&2 "!!! $po doesn't exist,
    is empty or is not a PO."; close_or_exit 1)

check_gnun_slot "$po"

# If a relative path has been entered, make it absolute.
test "${po#/}" != "$po" || po="$(pwd)"/$po

# Test whether the PO is in a www-related directory (www-team or even
# www-test or www); remove "po/" from the path in case it is in www.
podir=${po%/*}
poname=${po#*/www*/} && poname=${poname/po\//}
echo -e "\n=== $poname"
# Find the common root of www-* and www.
test "$poname" != "$po" && rootdir=${po%%\/www*}

# Get the language code from the name of the PO.
lang=${poname%.po}
if [ "${lang##*.}" != "$lang" ] ; then
  lang=${lang##*.}
else
  lang=${lang##*/}
fi

exit_code=0

## Reformat/validate the PO.
$MSGCAT -w 79 -o "$po" "$po" 1>&2 || (exit_code=$?; close_or_exit $exit_code)

check_fuzz "$po" || (exit_code=$?; $FUZZY_DIFF -i "$po";
  close_or_exit $exit_code)

if [[ "${poname}" =~ "proprietary/$lang.po" ]] && [ -n "$MSGMERGE" ]; then
  check_fuzz "$po" || (exit_code=$?; $FUZZY_DIFF -i "$p";
      close_or_exit $exit_code)
  find "$podir" -maxdepth 1 -name "*.$lang.po" | sed '/menu/d' | sort |
  while read p; do
    echo "" > $top
    sed -n '1,/Content-Transfer-Encoding:/p' "$p" > $top
    $MSGMERGE -N -C ${p%/*.*.po}/$lang.po /dev/null "$p" -o $merged
    sed -i '1,/Content-Transfer-Encoding:/d' $merged
    if [ -n "$top" ]; then
      cat $top $merged > "$p"
    else
      mv $merged "$p"
    fi
  done
  echo "*** Several malware files need to be validated along with $lang.po;
    (re)run transvalid-batch."; exit 5

else
  ## Get the original HTML.
  if test ! -f "$original"; then
    # Check whether the context is that of www.gnu.org, with the PO in
    # www-*/ and a valid original HTML in www/. Otherwise, ask for it
    # (except in case of batch transvalidation).
    original=$rootdir/www/$poname
    original=${original/.$lang.po/.html}
    if test ! -f "$original" -a -z "$batch"; then
      echo "*** Please enter the original file."; read original
    fi
    original=${original#\'}; original=${original%\'}
  fi

  test -s "$original" -a  "${original%.html}" != "$original" ||
    (exit_code=$?; echo 1>&2 "!!! $original doesn't exist,
    is empty or is not an HTML."; close_or_exit $exit_code)

  ## Prepare the po4a "master".

  fix_html "$original" "$master"
  remove_last_update "$master"
  add_split_tags "$master"

  ## Generate the translated page.

  translation="${po/.po/-local.html}"
  rm -f "$translation"

  if grep "*GNUN-SLOT" "$po" > /dev/null; then
  # If this is a normal gnu.org article:
    create_addendum "$po" NOTES 'footer.html"' "$add_notes"
    create_addendum "$po" CREDITS '/server/bottom-notes.html' "$add_credits"
    # The po4a-translate "k" option, “Minimal threshold for translation
    # percentage to keep (ie, write) the resulting file” according to the
    # manual, is set at 30 to allow proofreading of a partial translation
    # or detection of faulty strings (the default is 80).
    $PO4A_TRANSLATE -f xhtml -M utf-8 -m "$master" -p "$po" -k 0 -L utf-8 \
        -l "$translation" -a "$add_credits" -a "$add_notes" 2>/dev/null ||
        (exit_code=$?; close_or_exit $exit_code)
  else
    $PO4A_TRANSLATE -f xhtml -M utf-8 -m "$master" -p "$po" -k 0 -L utf-8 \
        -l "$translation" 2>/dev/null || (exit_code=$?; close_or_exit $exit_code)
  fi

  ## Validate and tweak the HTML.

  if test "$po" = "${po%/body-include-2.*.po}"; then
    $XMLLINT --dtdvalid $DTD/html5.dtd --nonet --noout "$translation" 1>&2 ||
        (exit_code=$?; close_or_exit $exit_code)
  fi
  make_links_absolute "$translation"
fi

## Tweak the PO.
if [ $lang="fr" ]; then
  fix_space "$po"
fi
if test "$delout" == "1"; then
  delete_outdated "$po"
fi
if test "$delobs" == "1"; then
  delete_obsolete "$po"
fi

# The PO header is updated in transvalid-batch. Uncomment if updating a
# single PO. Leave commented out if transvalid-po is used for validation only.
#update_po_header "$po"

echo '    OK'
exit $exit_code
