#!/bin/bash

# NAME
#    www-commit - batch commit to the www repository

# SYNOPSIS
#    www-commit .../www-TEAM

# DEPENDENCIES
#    required: cvs, git.

# DESCRIPTION
#    www-commit assumes the context of www.gnu.org, with the team directory
#    (www-team) under Git. It copies the modified POs from www-team to www, in
#    batches corresponding to the Git commits, then commits them to the www CVS
#    repository.
#
#    *** This script cannot commit files in server/gnun/compendia/.
#    *** They are not in a po directory as are the other POs.
#
#    Requirements:
#    * www and www-team must have the same parent directory.
#    * www-team must be a Git repository and contain the working copies of the
#      PO files.
#    * www must contain the PO files under CVS control.

# OPTIONS AND CURRENT SETTINGS
#    Displayed by:   www-commit -h
#
#    Configuration file:
#    The command-line parameters can be set once and for all in a configuration
#    file (also used by transvalid-batch, cvs-sync, micro-www-checkout and
#    check-links, with the syntax:
#       parameter1="value1"
#       parameter2="value2"
#    This configuration overrides the default settings but is superseded by the
#    command line. The file ($conf) is specified under "Parameters".

#==============================================================================

set -e
set -o pipefail

function version () {
cat <<EOF
${0##*\/} version 0.2
You may redistribute this script and/or modify it under the terms
of the Creative Commons Zero.
EOF
}

function usage () {
cat <<EOF

Usage: ${0##*\/} .../www-TEAM

  The script assumes the context of www.gnu.org, with the team directory
  (www-team) under Git. It copies the modified POs from www-team to www,
  in batches corresponding to the Git commits, then commits them to the
  www CVS repository. www and www-team must have the same parent directory.

Options:
  -V  Display version info and exit.
  -h  Display this help and exit.

Report bugs to <godef.th@free.fr>

EOF
}

function close_term () {
  echo -e '\n*** Close the terminal window or press Return.'; read OK
  test -z "$OK" && exit $1
}

function select_message () {
# lets the user select a message from the configuration file.
  echo -e "\n*** Please select a commit message:
        [0] I'll write it myself.
        [1] $message11
        [2] $message12
        [3] $message13
        [4] $message14
        [5] $message15
        [6] $message16
        [7] $message17
        [other] no commit"
  read -s -n1 choice
  case "$choice" in
    0) echo "What is the message?"; read message ;;
    1) message=$message11 ;;
    2) message=$message12 ;;
    3) message=$message13 ;;
    4) message=$message14 ;;
    5) message=$message15 ;;
    6) message=$message16 ;;
    7) message=$message17 ;;
    *) message= ;;
  esac
}

echo "${0##*\/} - batch commit to the www repository"

# Initial parameters
conf="$HOME/.profile"
teamdir=""
copyonly=""
test -s "$conf" && source $conf

# Parse the command line.
OPTIND=1
while getopts "h?V" opt; do
  case "$opt" in
    h | \? ) usage; exit 0 ;;
    V ) version; exit 0 ;;
  esac
done
shift $((OPTIND-1))
[ "$1" = "--" ] && shift

# Team directory input
test -n "$1" && teamdir=$1
if test ! -d "$teamdir"; then
  echo -e "\n*** Please specify your team directory."; read teamdir
fi
teamdir=${teamdir%\'}; teamdir=${teamdir#\'}
# Make sure it can be reached.
cd "$teamdir" \
|| (echo 1>&2 "!!! Can't reach $teamdir."; close_term 1)

lang=${teamdir##*www-}


# Create TMP files.
batch1=$(mktemp -t commit.XXXXXX) || exit 1
batch2=$(mktemp -t commit.XXXXXX) || exit 1
batch3=$(mktemp -t commit.XXXXXX) || exit 1
batch4=$(mktemp -t commit.XXXXXX) || exit 1
batch5=$(mktemp -t commit.XXXXXX) || exit 1
d=$(mktemp -t commit.XXXXXX) || exit 1
trap 'rm -f "$batch1" "$batch2" "$batch3" "$batch4" "$batch5" "$d"' EXIT

# Get lists of modified POs.
git diff --name-only www www^ > $batch1
git diff --name-only www^ www^^ > $batch2
git diff --name-only www^^ www^^^ > $batch3
git diff --name-only www^^^ www^^^^ > $batch4
git diff --name-only www^^^^ www^^^^^ > $batch5

# Copy and commit.
echo ''
n=0
for s in $batch1 $batch2 $batch3 $batch4 $batch5; do
  let n=n+1 
  echo -e "\n=== Batch #$n:\n"
  cat $s                                            # source list (in www-team)
  sed -i "/\\/master\\.$lang\\.po/d" $s

  echo "        [0] skip
        [1] copy only
        [2] commit
        [other] quit"
  read -s -n1 choice
  case "$choice" in
    0 ) continue ;;
    1 ) copyonly=1 ;;
    2 ) copyonly="" ;;
    * ) exit 0 ;;
  esac

  sed -e "s,\\([^/]*$lang\\.po\\),po/\\1," $s > $d  # destination list (in www)
  sfiles=($(< $s))                                  # source array
  dfiles=($(< $d))                                  # destination array

  i=0
  while [ "$i" -lt ${#sfiles[@]} ]; do
    cp ${sfiles[$i]} ../www/${dfiles[$i]}   # copy file from www-team to www
#    cp ${sfiles[$i]} /media/Gnu-local/www/${dfiles[$i]}
    let i=i+1
  done
  if [ -z "$copyonly" ]; then
    select_message
    if [ -z "$message" ]; then
      echo "No message. This batch will not be committed."
    else
      echo "cvs commit -m \"$message\" $(< $d)"
      echo "OK this commit."
      read -s -n1 OK
      if [ -z "$OK" ]; then
        cd ../www && cvs commit -m "$message" $(< $d) ||
          (echo 1>&2 "!!! Unable to commit"; close_term 1)
        echo "Done."
        cd $teamdir
      else
        echo "Copied to www; not committed."
      fi
    fi
  else
    echo "Copied to www; not committed."
  fi
done

exit 0
